### ISSUE TITLE
Navigation Problems 

### ISSUE THREAD

**Issue by SullivanPrell** [clearwater-labs/uwecApp#7]
Currently with the navigation buttons, I am hitting either the laundry or bus tracking button but instead, it takes me to the page directly next to it, so in the case of laundry I go to the spectator page. I am assuming this is an issue with the TouchableOpacity component - `lines 32` and `60` in the `App.js` file

**Comment by alex-stout** [comment]
On it.

**Comment by alex-stout** [comment]
It was a problem with the images. They were not correctly sized to the box.

So I did the following: 

- Switched around the way that the flex direction and wrapping are happening.

- Moved the `TouchableOpacity` around the `navigationBox` so that a touch on any of the box navigates to the route rather than just the image.


The layout still needs to be looked at and improved. Hopefully this helps.

My update commit: dd3f4df
